### ISSUE TITLE
derpibooru still not working

### ISSUE THREAD

**Issue by 99spooner** [DontTalkToMeThx/BooruSlideshowElectron#1]
so im not sure if it was added wrong or something but derpibooru still  dosnt seem to work even after 
you merged the files from [here](https://github.com/DontTalkToMeThx/BooruSlideshow/issues/6). i also tried this on the regular chrome version and it seemed to have the same effect. im not sure if it merged wrong or somehow @gmasil screwed it up

**Comment by DontTalkToMeThx** [comment]
I'll check it out when I have time tomorrow.

**Comment by gmasil** [comment]
In the [original repo](https://github.com/DontTalkToMeThx/BooruSlideshow) it works as expected with chrome. I quickly tried the electron app, but for me it doesn't react to anything at all, so I can't test it right now.

**Comment by DontTalkToMeThx** [comment]
I believe I solved the issue, I'll get a new upload asap, alternatively you can clone the repo from the newest commit and build it yourself, but I expect the changes to be live within 24 hours, as usual. If it isnt fixed within 24 hours, reopen this issue
