### ISSUE TITLE
just something about full screen

### ISSUE THREAD

**Issue by 99spooner** [DontTalkToMeThx/BooruSlideshowElectron#2]
so i have been having this small problem for a while but didnt want to ask as i have already asked for many features or fixes previously but i feel it been a while enough, 

so whenever i have the app open i am not able to make other things such as firefox go fullscreen by pressing f11 (although i still can by pressing a button in the menu) , usually what will happen is even if i have it minimized and am on a browser it will just cause the app to go fullscreen in the background.  

its not that big a deal if you cant figure it out for some reason as there are workarounds but i would help to make it even better

**Comment by DontTalkToMeThx** [comment]
I noticed that with all shortcuts I added, and I'm not sure why it's accepting shortcuts while minimized, I can look at it though.

**Comment by DontTalkToMeThx** [comment]
Will be fixed within 24 hours, reopen this if not.

**Comment by DontTalkToMeThx** [comment]
This one will take a bit longer, I'll be sure to have it done within 12 hours though, I just need to upload it, but I can't at the moment.

**Comment by 99spooner** [comment]
No problem dude take all the time you need (within reason), better late then never
