### ISSUE TITLE
ATFBooru Error

### ISSUE THREAD

**Issue by BigBonger** [DontTalkToMeThx/BooruSlideshowElectron#3]
Error making the request to https://atfbooru.ninja/posts.json?tags=a&page=1&limit=100

This is the error I get, how can I fix this?

**Comment by Zeddylegend** [comment]
That website is down, the new one is "https://booru.allthefallen.moe/"  or at least i think so...

**Comment by Zeddylegend** [comment]
It would be awesome if we had some way to talk with him :/

**Comment by DontTalkToMeThx** [comment]
I've updated the URL. I didn't get any notifications for this thread so I never saw it. You should be able to download it from the links in the README.

**Comment by Zeddylegend** [comment]
> I've updated the URL. I didn't get any notifications for this thread so I never saw it. You should be able to download it from the links in the README.

Thanks for the fix, the links in the readme doesnt work for me, it says "the conection is not private" NET::ERR_CERT_DATE_INVALID

**Comment by DontTalkToMeThx** [comment]
> > I've updated the URL. I didn't get any notifications for this thread so I never saw it. You should be able to download it from the links in the README.
> 
> Thanks for the fix, the links in the readme doesnt work for me, it says "the conection is not private" NET::ERR_CERT_DATE_INVALID

Sorry about that, should be fixed now.
