### ISSUE TITLE
Danbooru tag number / content filter

### ISSUE THREAD

**Issue by hpcjosh** [DontTalkToMeThx/BooruSlideshowElectron#4]
Thanks for keeping the app updated along with the Pahel addition, however one flaw with the electron app is that there's no API key entry for danbooru to get around their tag number/content limit. With the Chrome/Firefox extension this can be worked around by 
logging in first and using the app as it will just use the log-in cookie to "authenticate" the account browsing. 

I suggest adding a field for the API key or a link to allow you to log in on their website.

**Comment by DontTalkToMeThx** [comment]
I will need to look into if their api allows for it. If it does, I will add this feature

**Comment by DontTalkToMeThx** [comment]
I added this feature, as we speak the files are being uploaded on to the server for download. From what I've tested, it works, let me know if you experience problems. **I will close this issue and edit this comment once all files are uploaded, until then you may download an outdated version, so please be patient.**
