### ISSUE TITLE
Gelbooru API

### ISSUE THREAD

**Issue by Certwastaken** [DontTalkToMeThx/BooruSlideshowElectron#7]
Pretty sure the Gelbooru API changed, breaking it for BooruSlideshow

**Comment by DontTalkToMeThx** [comment]
Newest release adds a place to put your gelbooru api key and user id. You can get those at the bottom of [this page](https://gelbooru.com/index.php?page=account&s=options). Copy them separately. The value comes after the `=` and before the next `&`. If you double click between that, you'll probably get the right stuff. Example of a user id: `506145`. Example of an api key: `b5ceb7137a1d6f51a66149026a51dfab388b7195cf6ff390e12761b15ea6d1ff`. The update has been added to the downloads page.
