### ISSUE TITLE
Search button not working

### ISSUE THREAD

**Issue by LunaTheBronyGamer** [DontTalkToMeThx/BooruSlideshowElectron#9]
every other button works in the app but i can't search anything,is this a bug? Please let me know thank you :D

**Comment by LunaTheBronyGamer** [comment]
i can't click on it at all,it does literally nothing :(

**Comment by DontTalkToMeThx** [comment]
Going to need slightly more info such as what sites are you searching, and what is the search text you are using. Since it works on my end, it's a little hard to tell what's going on for you

**Comment by LunaTheBronyGamer** [comment]
All websites do not work,and even pressing the enter button when i typed my
tags it doesn't work either

**Comment by LunaTheBronyGamer** [comment]
It happends in both the app and when i open the html link,both have the
same issue

**Comment by LunaTheBronyGamer** [comment]
And i use rule34 tags,just like they are shown on rule34,so i dunno why its
broken i tested it on the old browser extension version and there it did
work,so i think it might be a bug

**Comment by LunaTheBronyGamer** [comment]
I also tested it on my extra linux pc with the linux version,same result as
the windows version

**Comment by LunaTheBronyGamer** [comment]
I explained all the issues below,should be enough information,if you need
more information please let me know

**Comment by LunaTheBronyGamer** [comment]
Did you try to look into it? Just wondering cause of the amount of info i gave you,please let me know thx 😁

**Comment by DontTalkToMeThx** [comment]
I'll look into it, but I don't have the issue or work on this project actively anymore. If it's something I can quickly identify and fix, I'll get a new version out for you.

**Comment by DontTalkToMeThx** [comment]
Yeah, just built the latest version, selected rule34 and searched "female" and it worked as expected
![example](https://oliy.is-just-a.dev/sk2qg_17729.png)

**Comment by DontTalkToMeThx** [comment]
Can you use `Ctrl+Shift+i` and go to console, type in some tags, press search and send me a screenshot of the console afterwards?

**Comment by LunaTheBronyGamer** [comment]
[image: Capture.PNG]

**Comment by DontTalkToMeThx** [comment]
You'll have to go onto github to upload the image.

**Comment by LunaTheBronyGamer** [comment]
Ok i'll do it once i get home from work

**Comment by LunaTheBronyGamer** [comment]
![Capture](https://github.com/DontTalkToMeThx/BooruSlideshowElectron/assets/105565648/9c0ac19d-97d3-468f-b0a1-fc6b967bda8c)

**Comment by DontTalkToMeThx** [comment]
How are you starting the app? Did you build it? Or are you using `npm start`?

**Comment by DontTalkToMeThx** [comment]
I've also pushed a change which may fix it.

**Comment by LunaTheBronyGamer** [comment]
![Capture](https://github.com/DontTalkToMeThx/BooruSlideshowElectron/assets/105565648/e04b2fec-a6e0-4642-91c7-276572e884d8)
New error

**Comment by DontTalkToMeThx** [comment]
Yeah, I'm not sure then, I've got it working on my end with the changes I just made. That error is actually the same one. For some reason it can't find the app, which doesn't make sense, but any other deep code changes are pretty much out of scope for this project as I've moved on from it. You can potentially try building from a specific commit, but I'm not sure that will help as the issue stems from a required module that's been in the app since release.

**Comment by SpotPot** [comment]
When building I noticed that there were errors relating to the versions of dependencies. I'm too much of a buffoon to figure how to grab those specific versions so uh. There's that.

**Comment by DontTalkToMeThx** [comment]
I uploaded a windows build here: https://file.io/Vy3N87AF1gNZ. Should work

**Comment by LunaTheBronyGamer** [comment]
the search button does work yes,but it never loads the images,like it does show that its trying to search but it never loads the images no matter the tag
![Capture](https://github.com/DontTalkToMeThx/BooruSlideshowElectron/assets/105565648/c686357f-a35e-406a-abf6-c124d03e675c)

**Comment by DontTalkToMeThx** [comment]
Let's try it again: https://uploadnow.io/f/DyLgv3W

**Comment by LunaTheBronyGamer** [comment]
![Capture](https://github.com/DontTalkToMeThx/BooruSlideshowElectron/assets/105565648/099a5d7d-2a4f-4798-98e2-13729a2d1136)
It does finish loading now but when it finishes still no images show up,also here is the error

**Comment by DontTalkToMeThx** [comment]
https://uploadnow.io/f/BYWB2Sy Ok, if this doesn't work, then I don't know. I personally have tested every build and they all worked, so I'm not sure why it hasn't been.

**Comment by LunaTheBronyGamer** [comment]
I honestly don't know what is wrong with it either,cause the older builds worked fine for me

**Comment by LunaTheBronyGamer** [comment]
But imma test it

**Comment by LunaTheBronyGamer** [comment]
I think its fixed now thanks!

**Comment by DaniNyo** [comment]
Hey, I am having the same issue on my end, I can click around to the favorite menu, but no other search itself just won't work.
